export const TODO_PENDING = 'TODO_PENDING';
export const TODO_REJECTED = 'TODO_REJECTED';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
